name: Deployment Workflow



on:

  push:

    branches:

      - main



jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - run: npm install
      - run: |
          system('git config --global user.email "uditmalhotra98@gmail.com"')
          system('git config --global user.name "Udit Malhotra"')
      - run: npm run deploy
